meta_product_name: "Talentr"
meta_title: "Talentr - A data driven way to hire!"
meta_description: "Talentr allows you to stop making hiring decisions on a hunch. Inform your candidate screening by analysing candidate profiles via a data dashboard. Perform queries and add filters on multiple data points to establish the best candidates for the role! Your business deserves best!"
meta_image: "analysis.png" # should exist in `app/assets/images/`
twitter_account: "@talentrio"   # required for Twitter Cards
